### ISSUE TITLE
EffectLib

### ISSUE THREAD

**Issue by mikassio** [nisovin/MagicSpells#33]
Hi, I would like to ask you , do Effectlib support for Minecraft 1.7.10. I have a server on Kcauldron, but as you know , for version 1.8 does not have a nucleus ( with mods and plugins at once) . Sorry for my english .

**Comment by tara81** [comment]
Effectlib is only implemented in the magicspells fork created by computergeek , not the main magicspells plugin hehe.

**Comment by mikassio** [comment]
Let them implemented in 1.7.10 , what's the problem ?

**Comment by tara81** [comment]
Your making a ticket in the wrong bug reports. This is for nisovins magicspells, not geeks forked version.

**Comment by DragonsAscent** [comment]
1.7.10 will also never be supported. I'm answering for those whom still read this.

Cauldron and any of it's forks are dead. We will never support them.
